artifact_location: /home/jj/github-classroom/STRDeepRL/week-1-intro-to-deep-rl-and-agent-training-environments-jsa1142/submission/mlflow/778391136765164625
creation_time: 1694631144114
experiment_id: '778391136765164625'
last_update_time: 1694631144114
lifecycle_stage: active
name: penalty_0.002
